# Generated by Django 5.0.4 on 2024-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
